/// Flutter icons MuzeIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MuzeIcons
///      fonts:
///       - asset: fonts/MuzeIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MuzeIcons {
  MuzeIcons._();

  static const _kFontFam = 'MuzeIcons';

  static const IconData discover = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData mylist = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe82a, fontFamily: _kFontFam);
}
